### ISSUE TITLE
S3 upload returns bucket not exisiting

### ISSUE THREAD

**Issue by commandantp** [CoreProc/laravel-db-backup#1]
Hi,

It's all in the title, :-) 
Ended up using schickling's package again but wanted to let you know something might be off.

**Comment by chrisbjr** [comment]
Hi commandantp

Did you follow the instructions on the README? You'll need to set up your
AWS credentials first.

I'm not sure what's happening with your set up but we have more than a
dozen web apps  running backups with this and uploading to S3. Also, this
is using the AWS library so if it says that the bucket is not found, then
it's likely that the bucket really doesn't exist.

**Comment by commandantp** [comment]
Ummm strange I changed nothing but worked with the other one. I'll see if I can try again one of those days
